// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akbxpedeouflujvlfhqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYnhwZWRlb3VmbHVqdmxmaHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzg5OTksImV4cCI6MjA3MzQxNDk5OX0.U0x_Ft5r0NZalJwdGjKxutuFcueWHz8zXrNa3orbBIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});